name: build
on:
  - push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-node@v1
      with:
        node-version: 12.x
    - name: run ci
      run: |
        pwd
        echo "$pwd/a/b/c"
        node common/scripts/install-run-rush.js install
        node common/scripts/install-run-rush.js build
        node common/scripts/install-run-rush.js lint
