name: build
on:
  - push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-node@v1
      with:
        node-version: 12.x
    - name: run ci
      run: |
        node common/scripts/install-run-rush.js install

        CHANGEFILE_JS=/home/runner/work/rush-learning/rush-learning/common/temp/install-run/@microsoft+rush@5.34.0-pr2172.0/node_modules/@microsoft/rush-lib/lib/api/ChangeFile.js
        TIMESTAMP_FN='_getTimestamp(useSeconds = false) {'

        sed -i "s~$TIMESTAMP_FN~$TIMESTAMP_FN\nreturn 'pr' // patched_timestamp;~g" $CHANGEFILE_JS
        cat $CHANGEFILE_JS | grep patched_timestamp
        echo grepping for nonexistent line
        cat $CHANGEFILE_JS | grep something_that_does_not_exist

        node common/scripts/install-run-rush.js build
        node common/scripts/install-run-rush.js lint
