name: create change files
on:
  - pull_request

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-node@v1
      with:
        node-version: 12.x
    - name: crupdate change files
      env:
        PR_BODY: ${{ github.event.pull_request.body }}
        PR_TITLE: ${{ github.event.pull_request.title }}
        PR_NUMBER: ${{ github.event.pull_request.number }}
      run: |
        node common/scripts/install-run-rush.js install

        CHANGEFILE_JS=/home/runner/work/rush-learning/rush-learning/common/temp/install-run/@microsoft+rush@5.34.0-pr2172.0/node_modules/@microsoft/rush-lib/lib/api/ChangeFile.js
        TIMESTAMP_FN='_getTimestamp(useSeconds = false) {'

        echo "patching $TIMESTAMP_FN in $CHANGEFILE_JS"
        sed -i "s~$TIMESTAMP_FN~$TIMESTAMP_FN\nreturn 'pr_$PR_NUMBER' // patched_timestamp;~g" $CHANGEFILE_JS

        echo "grepping for patched code, this will fail if rush code changed recently, and the sed command didn't replace anything"
        cat $CHANGEFILE_JS | grep patched_timestamp

        BUMP_TYPE=minor
        IS_MAJOR=$(echo "$PR_TITLE $PR_BODY" | grep 'BREAKING CHANGE' || echo '')
        IS_PATCH=$(echo "$PR_TITLE" | grep '^fix' || echo '')
        echo "is patch $IS_PATCH ..."
        if [ -n "$IS_MAJOR" ]; then
          BUMP_TYPE=major
        elif [ -n "IS_PATCH" ]; then
          BUMP_TYPE=patch
        fi

        git config --global user.email "${{ github.actor }}@users.noreply.github.com"
        git config --global user.name "${{ github.actor }}"
        git checkout ${{ github.head_ref }}

        node common/scripts/install-run-rush.js change --message "$PR_TITLE" --overwrite --bulk --bump-type $BUMP_TYPE

        if expr $(git status --porcelain | wc -l) \> 0
        then
          git add -A
          git commit -m "chore: change files"

          remote_repo="https://${{ github.actor }}:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git"
          git push "${remote_repo}"
        else
          echo "no changes made"
        fi
